### ISSUE TITLE
Support for dynamic interventions that are a function of observables

### ISSUE THREAD

**Issue by agrawalraj** [BasisResearch/chirho#163]
In practice, we don't know the true value of the states because the ODE dynamics are modeled as latents. Our current implementation of dynamic interventions assumes that we know the true values of the state at any point in time. We should allow users to perform dynamic interventions as a function of the observed values in a model's `observation` method. @SamWitty thinks doing such dynamic interventions will result in an SDE, which might create some methodological challenges before we can add such a feature.

**Comment by eb8680** [comment]
I'm not sure this is relevant anymore after #340. I think it should be possible to express whatever was intended here by including the relevant variables in the system state. Whether the resulting dynamical systems are supported by any backend is a separate question that deserves its own up-to-date issue.
