### ISSUE TITLE
Add instrumental variables example

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#18]
As in the other examples, the easiest way to approach this is probably to pick a single paper and reproduce its model and results.

Some candidate papers:
- [Mendelian randomization](https://journals.sagepub.com/doi/10.1177/0962280215597579)
- [Deep instrumental variables](https://arxiv.org/abs/1612.09596)

**Comment by qinqian** [comment]
A relevant about the Mendelian randomization: https://www.nature.com/articles/s41467-023-41394-4.

**Comment by dimkab** [comment]
Published version of the Deep IV paper:

J. Hartford, G. Lewis, K. Leyton-Brown, and M. Taddy, “Deep IV: A Flexible Approach for Counterfactual Prediction,” in Proceedings of the 34th International Conference on Machine Learning, PMLR, Jul. 2017, pp. 1414–1423.  Available: https://proceedings.mlr.press/v70/hartford17a.html
