### ISSUE TITLE
Each module should have its own installation requirements

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#202]
This will make dependency management easier in the future, e.g. `pip install chirho[interventional,indexed]`

**Comment by SamWitty** [comment]
Looking into this a bit more it's not obvious that there's anything to be done for existing modules, as they all appear to only depend on pyro. Instead, it seems like the thing to do would be to module options if and only if those modules require additional dependencies. torchdiffeq in the `dynamical` module in the now revised #299 is a good example.

**Comment by SamWitty** [comment]
Closing as I believe this is addressed by my comment above. Feel free to reopen if you believe this was closed by mistake.
