### ISSUE TITLE
Explanatory figures in deployed tutorial are inconsistent with source jupyter notebook

### ISSUE THREAD

**Issue by SamWitty** [BasisResearch/chirho#207]
In our tutorial we walk through a collection of 4 explanatory conceptual figures showing how uncertainty is propagated through causal models, factual/counterfactual data, and causal queries to set the stage for causal inference as probabilistic inference.

Currently, our deployed tutorial (https://basisresearch.github.io/chirho/tutorial_i.html#) simply shows the final schematic repeated 4 times.

<img width="978" alt="Screenshot 2023-07-10 at 10 49 10 PM" src="https://github.com/BasisResearch/chirho/assets/13202375/d1b643c7-0ce0-4d63-bf27-ad8760fe4c13">

----------------------------------------------------------------

<img width="978" alt="Screenshot 2023-07-10 at 10 49 30 PM" src="https://github.com/BasisResearch/chirho/assets/13202375/13e5d907-416c-419e-a9f5-ba0959a405f1">

----------------------------------------------------------------

<img width="978" alt="Screenshot 2023-07-10 at 10 49 56 PM" src="https://github.com/BasisResearch/chirho/assets/13202375/25bc272d-e6be-40b5-a277-351ee35b237b">

----------------------------------------------------------------

<img width="978" alt="Screenshot 2023-07-10 at 10 50 17 PM" src="https://github.com/BasisResearch/chirho/assets/13202375/f88c8312-5552-474a-802a-863b40e82487">

----------------------------------------------------------------

This is not replicated in the source tutorial notebook, which correctly refers to each of the four unique figures.
https://github.com/BasisResearch/chirho/blob/master/docs/source/tutorial_i.ipynb

**Comment by eb8680** [comment]
Does this happen when you build docs from source locally?

**Comment by eb8680** [comment]
Fixed in #209
