### ISSUE TITLE
Add single-cell RNA seq example

### ISSUE THREAD

**Issue by agrawalraj** [BasisResearch/chirho#237]
We can look at this open-source project to easily load in single-cell RNA seq data in batches in pytorch:

https://chanzuckerberg.github.io/cellxgene-census/notebooks/experimental/pytorch.html

**Comment by agrawalraj** [comment]
When I tried installing `cellxgene-census`, the `alias` dependency requires version 23.1.0 or above. I initially had an earlier version and got the error `TypeError: field() got an unexpected keyword argument 'alias'`. To use the PyTorch dataloader by importing `import cellxgene_census.experimental.ml as census_ml`, you need to install `torchdata`.

**Comment by qinqian** [comment]
scvi has a more mature api for batch operation of single cell data with pytorch datasets. please see [here](https://github.com/scverse/scvi-tools/blob/1.0.3/scvi/data/_manager.py#L50-L533).
