### ISSUE TITLE
Docs build is failing upon deployment to GH pages

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#243]
This first happened after #238 was merged, but I haven't had any issues building docs locally and the CI docs build worked fine in #238. It's probably something to do with the versions of the requirements in `docs/requirements.txt`.

The previously deployed version of the docs is still up, so we should resolve this soon but it doesn't have to happen immediately.

Log here: https://github.com/BasisResearch/chirho/actions/runs/6049890251/job/16425678930

**Comment by SamWitty** [comment]
I'll hunt down the culprit dependencies.

**Comment by eb8680** [comment]
Two things to try are building from the commit prior to #238 to see if it still fails and pinning the PyTorch and Pyro versions.

**Comment by SamWitty** [comment]
Tried checking out the commit prior to #238 and pinning PyTorch and Pyro versions and still no success. I also went with the nuclear option and pinned all of the dependencies in `docs/source/requirements.txt` to the following and still no success.

```
pyro-ppl==1.8.5
jupyter
mypy==1.5.0
sphinx==7.2.2
sphinxcontrib-bibtex==2.5.0
sphinx_rtd_theme==1.3.0
myst_parser==2.0.0
nbsphinx==0.9.2
```

**Comment by eb8680** [comment]
By "no success," do you mean you're getting exactly the same error?
