### ISSUE TITLE
`@pyro.poutine.block` decorator causes documentation to fail to render

### ISSUE THREAD

**Issue by SamWitty** [BasisResearch/chirho#272]
As briefly discussed (and misdiagnosed) in #269 and #270, the current docs build fails to render some operations. Some preliminary exploration points to this being a problem with the `@pyro.poutine.block` decorator, e.g. used in the `counterfactual.split` operations here https://github.com/BasisResearch/chirho/blob/master/chirho/counterfactual/ops.py#L13.

Currently, with the `@pyro.poutine.block` decorator the documentation renders as follows:
<img width="953" alt="Screenshot 2023-09-19 at 2 26 23 PM" src="https://github.com/BasisResearch/chirho/assets/13202375/6f3b12d1-a1f7-4f01-a2ed-73110bd2967b">

However, when I comment out only https://github.com/BasisResearch/chirho/blob/master/chirho/counterfactual/ops.py#L13 and run the docs build locally I get the following:
<img width="953" alt="Screenshot 2023-09-19 at 2 27 08 PM" src="https://github.com/BasisResearch/chirho/assets/13202375/fa8c4794-0e93-44a5-850b-1fe142072387">

Note: getting the documentation to render does not require commenting out the `@pyro.poutine.runtime.effectful` decorator at https://github.com/BasisResearch/chirho/blob/master/chirho/counterfactual/ops.py#L12C1-L12C46. In addition, commenting out the `@pyro.poutine.runtime.effectful` decorator without commenting out the `@pyro.poutine.block` decorator does not fix the problem.

**Comment by eb8680** [comment]
I will look for a workaround tonight.
