### ISSUE TITLE
Notebooks should be rerun in CI or periodically

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#283]
This would help catch bugs like #273 when they are introduced.

**Comment by SamWitty** [comment]
Note: For a first pass, we can just run the tutorial notebook(s) using `pytest --nbval-lax docs/source/tutorial_i.ipynb`

**Comment by SamWitty** [comment]
@rfl-urbaniak , any update on this? I'm happy to take it on if you're busy.

**Comment by rfl-urbaniak** [comment]
Running into deadlines on other projects and so postponing all the time. Apologies. Will focus on this on Wednesday once a Tuesday deadline in another project is met.
