### ISSUE TITLE
Refactor dynamical module file structure to be consistent with other modules

### ISSUE THREAD

**Issue by SamWitty** [BasisResearch/chirho#287]
Currently the dynamical systems module in `staging-dynamic` has operations, handlers, and private methods mingled together in various files. Instead, the file structure should reflect other modules in `chirho`, namely where the module is separated into `ops`, `handlers`, and `internals` according to the following structure.

ops -> User-facing classes and operations for representing dynamical systems, dynamical system state, and dynamical system trajectories.
handlers -> User-facing effect handlers for manipulating dynamical systems simulations.
internals -> Everything else.

**Comment by eb8680** [comment]
Dupe of #156?

**Comment by SamWitty** [comment]
Yes, and addressed by #287. Closing both.
