### ISSUE TITLE
Implement log-joint probability of arbitrary new data

### ISSUE THREAD

**Issue by agrawalraj** [BasisResearch/chirho#368]
Given our guide with parameters $\phi$, we need to compute $\log p(x \mid \phi) = \mathbb{E}_{\theta \sim q(\theta \mid \phi)} \log p(x \mid \theta)$ 

and $\nabla_{\phi} \log p(x \mid \phi)$. See also "Option 2" in "Computing linearize for an arbitrary parametric guide" here: https://www.notion.so/basisresearch/Design-document-robust-statistics-with-influence-functions-0a3ecaab5b944e2fade867a6958039b7.

**Comment by eb8680** [comment]
Addressed in #384
