### ISSUE TITLE
Implement interface for functionals

### ISSUE THREAD

**Issue by agrawalraj** [BasisResearch/chirho#369]
Currently, a functional is of type `Functional = Callable[[Callable[P, T]], Callable[P, R]]`. If we treat a functional as a PyTorch function, we just need to be able to compute it at a model and guide, and take gradients. Hence, a functional should have a `foward` and `grad` method.

**Comment by eb8680** [comment]
I think this is addressed in #384 by defining `Functional` more carefully.
