### ISSUE TITLE
Set up Sphinx gallery of example notebooks

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#38]
Documentation: https://sphinx-gallery.github.io/stable/index.html

See NumPyro's landing page as an example: https://num.pyro.ai/en/stable/

**Comment by SamWitty** [comment]
@eb8680 , can this be closed?

**Comment by eb8680** [comment]
No, it would still be nice to do this at some point

**Comment by eb8680** [comment]
I'm just going to close this, I think it will be a pain to get it working with the README file duplication setup from #191
