### ISSUE TITLE
PyTorch function transforms are not compatible with PyroParams

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#393]
In `chirho.robust`, we're making extensive use of `torch.func`, especially the vectorization transform `torch.func.vmap` and forward and reverse-mode autodiff transforms `torch.func.jvp`/`vjp`.

Unfortunately, the autodiff transforms seem to be fundamentally incompatible with `PyroModule`s that have constrained `PyroParam`s, including most of the standard autoguides in `pyro.infer.autoguide` - the raw PyTorch `Parameter` tensors underlying the constrained `PyroParam`s do not seem to receive or propagate gradients. It's not clear what exactly in Pyro is causing the problem or how to fix or work around it, although it at least doesn't seem specific to ChiRho.

This isn't immediately blocking other work, but without compatibility with `PyroModule`s the practical utility of `chirho.robust` will be significantly diminished, so we should try to resolve this somehow before merging #398  into `master`.

**Comment by eb8680** [comment]
This should be resolved once a version of Pyro including https://github.com/pyro-ppl/pyro/pull/3328 is released.

**Comment by agrawalraj** [comment]
Ok that's awesome, thanks!

**Comment by eb8680** [comment]
Resolved in the Pyro 1.9.0 release
