### ISSUE TITLE
Missing documentation in `chirho.robust`

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#394]
This issue tracks work toward adding documentation for the components of `chirho.robust`:
- [x] `ops`
- [x] `internals.linearize`
- [x] `internals.predictive`
- [x] `internals.utils`
- [x] `handlers` (when populated)

**Comment by agrawalraj** [comment]
We'll get to this issue once we're done with #373

**Comment by agrawalraj** [comment]
Closed by #470
