### ISSUE TITLE
implement `explainable.ops.consequent_differs`

### ISSUE THREAD

**Issue by rfl-urbaniak** [BasisResearch/chirho#417]
Before `soft_eq` and `soft_neq` are implemented, tested, experimented with, the original functionality of `consequent_differs` needs to be refactored into the new `explainable` module, to reach the stage at which notebooks can be merged and be in presentable shape even before further moves with the soft version are made.

**Comment by eb8680** [comment]
@rfl-urbaniak are you going to create new issues for implementing `soft_neq` and updating `consequent_differs`, or should I leave this one open?

**Comment by rfl-urbaniak** [comment]
@eb8680,  I opened a new one, #455 , so I'm closing this one.
