### ISSUE TITLE
Consider removing separate `guide` argument from `influence_fn`

### ISSUE THREAD

**Issue by eb8680** [BasisResearch/chirho#477]
In our design for `chirho.robust`, we chose to parametrize the operations `linearize` and `influence_fn` with an unnormalized model and normalized guide. However, it turns out that the guide argument is only used directly to construct the model's posterior predictive distribution.

This observation was formalized in the recent refactoring PR #473 which added a helper function `chirho.robust.internals.predictive.PredictiveModel` and changed the rest of the code so that it only ever interacts with the guide through `PredictiveModel`.

This suggests that we could simplify many of the interfaces in `chirho.robust`, including the user-facing `influence_fn` and the `Functional` interface type, by removing their guide arguments and requiring the model argument to be normalized (e.g. because it is a `PredictiveModel` instance constructed by the user).

Tasks:
- [x] Make `functional` argument required #487 
- [x] Remove `guide` argument #489

**Comment by SamWitty** [comment]
This sounds great to me. This would also allow for a further separation of concerns between the inference method and the robust estimation functionality introduced in this module, and probably make it easier to port over other PPL backends in the future.

**Comment by agrawalraj** [comment]
+1 I think this is a great idea

**Comment by eb8680** [comment]
Resolved by #489
