### ISSUE TITLE
Annotating tutorial notebooks

### ISSUE THREAD

**Issue by sabinala** [BasisResearch/chirho#513]
Adding comments to code and clarifying text in ChiRho tutorial notebooks

**Comment by sabinala** [comment]
Handling this issue in a forked repository.

**Comment by SamWitty** [comment]
@sabinala , could you clarify where you think the tutorials and examples could use more documentation? At present, this issue is too underspecified to be addressed.

**Comment by sabinala** [comment]
Sure, I'm going to close this issue for now and revisit with more specificity another time.
