### ISSUE TITLE
Search doesn't work on basisresearch.github.io

### ISSUE THREAD

**Issue by dimkab** [BasisResearch/chirho#569]
Writing a query and hitting enter produces the following:

<img width="467" alt="image" src="https://github.com/user-attachments/assets/4a1a5052-c564-4ae3-b272-1d20b5b9507d">

**Comment by eb8680** [comment]
Thanks for catching this. Does search work when you build the docs locally?

**Comment by dimkab** [comment]
No, same problem. Looking at the page inspector gives the error:  "Query is not defined" in search.html lines 142,147. Tested with Chrome, Safari and Firefox on Mac.

**Comment by dimkab** [comment]
Looks relevant: https://github.com/sphinx-doc/sphinx/issues/7405

**Comment by dimkab** [comment]
adding   "sphinxcontrib.jquery" to the list of extensions in conf.py should do the trick (checked locally).

**Comment by eb8680** [comment]
Great, can you open a PR with a fix? Thanks
